import React from 'react';
import { Diagram } from '../Diagram';

/**
 * SectionIntro component.
 */
export default function SectionIntro() {
    return (
        <>
<section className="section" id="sec-1" tabIndex={-1}>{' '}<h2>0. 最初にお読みください（重要：名称変更について）</h2>{' '}<div className="prose">{' '}<p>{' '}ご指定の Cisco Japan のページは{' '}<strong>「Cisco Certified DevNet Associate」／試験名「200-901 DEVASC」</strong>{' '}の表記で、ページ上の最終更新表示は 2024 年です。その後、Cisco は{' '}<strong>2026 年 2 月 3 日</strong>{' '}から DevNet 認定を{' '}<strong>Automation トラック</strong>{' '}へ改称しました。Cisco Learning Network
                        の案内では、CCNA Automation の試験内容は従来の 200-901 DEVASC
                        から変更されず、<strong>試験名のみが更新される</strong>{' '}とされています。{' '}</p>{' '}<div className="table-wrap">{' '}<table><thead><tr><th scope="col">項目</th><th scope="col">旧名称</th><th scope="col">現在の名称</th></tr></thead><tbody><tr><td>認定名</td><td>Cisco Certified DevNet Associate</td><td><strong>CCNA Automation</strong></td></tr><tr><td>試験コード</td><td>200-901</td><td>200-901（同じ）</td></tr><tr><td>試験略称</td><td>DEVASC</td><td><strong>CCNAAUTO</strong></td></tr><tr><td>試験名</td><td>DevNet Associate Exam</td><td>Automating Networks Using Cisco Platforms</td></tr><tr><td>上位認定</td><td>DevNet Professional / Expert</td><td>CCNP Automation / CCIE Automation</td></tr></tbody></table>{' '}</div>{' '}<ul>{' '}<li>{' '}既存の DevNet Associate 保有者は、自動的に CCNA Automation
                            として扱われます（Certmetrics のプロファイルで確認できます）。{' '}</li>{' '}<li>{' '}本ガイドでは、検索や過去教材との照合がしやすいよう{' '}<strong>「DevNet Associate（CCNA Automation）」</strong>{' '}と併記します。{' '}</li>{' '}<li>{' '}<strong>注意</strong>：Cisco 公式の試験範囲（Exam
                            Topics）は予告なく変更される場合があります。受験前に必ず最新版を確認してください（URL
                            は巻末）。{' '}</li>{' '}</ul>{' '}<h3>0.1 本ガイドの試験範囲の根拠と限界</h3>{' '}<div className="table-wrap">{' '}<table><thead><tr><th scope="col">区分</th><th scope="col">内容</th></tr></thead><tbody><tr><td>章立て・配点・項目番号</td><td>Cisco 公式の 200-901 Exam Topics（v1.0 PDF）に基づく</td></tr><tr><td>v1.1 での用語変更</td><td>{' '}Webex Teams → Webex、DNA Center → Catalyst Center、SD-WAN →
                                        Catalyst SD-WAN、AMP → Secure Endpoint、ThreatGrid → Secure
                                        Malware Analytics など（公式 Exam Topics
                                        の抜粋と第三者解説で確認）{' '}</td></tr><tr><td>限界</td><td>{' '}最新 v1.1 の公式 PDF
                                        全文は取得できていません。項目番号や細かな文言が異なる可能性があるため、<strong>最終確認は公式ページで行ってください</strong>{' '}</td></tr></tbody></table>{' '}</div>{' '}</div>{' '}</section>

<section className="section" id="sec-2" tabIndex={-1}>{' '}<h2>1. 認定の全体像</h2>{' '}<div className="prose">{' '}<h3>1.1 認定のサマリー</h3>{' '}<div className="table-wrap">{' '}<table><thead><tr><th scope="col">項目</th><th scope="col">内容</th></tr></thead><tbody><tr><td>認定の目的</td><td>{' '}Cisco
                                        プラットフォーム上のアプリケーション開発・運用（自動化）に関する基礎スキルの証明{' '}</td></tr><tr><td>必要な試験</td><td><strong>1 つのみ</strong>（200-901）</td></tr><tr><td>試験時間</td><td>120 分</td></tr><tr><td>試験言語</td><td>英語・日本語</td></tr><tr><td>受験料</td><td>300 USD（Cisco Learning Credits も利用可能）</td></tr><tr><td>有効期間</td><td>3 年（再認定ポリシーに従う）</td></tr><tr><td>公式の前提条件</td><td>なし</td></tr><tr><td>推奨経験</td><td>1 年以上の Python を含むソフトウェア開発経験</td></tr><tr><td>推奨トレーニング</td><td>{' '}Developing Applications and Automating Workflows using Cisco
                                        Core Platforms（DEVASC）／ Cisco U. の学習パス{' '}</td></tr><tr><td>合格点</td><td>Cisco は公表していません</td></tr></tbody></table>{' '}</div>{' '}<h3>1.2 どんな人に向いているか</h3>{' '}<div className="table-wrap">{' '}<table><thead><tr><th scope="col">役割</th><th scope="col">この認定で得られるもの</th></tr></thead><tbody><tr><td>ネットワークエンジニア</td><td>CLI 手作業から API・スクリプトによる自動化への移行力</td></tr><tr><td>ソフトウェア開発者</td><td>{' '}ネットワーク／インフラを「プログラムから扱う」ための基礎知識{' '}</td></tr><tr><td>DevOps／SRE</td><td>CI/CD・IaC・コンテナをネットワーク領域へ適用する視点</td></tr><tr><td>初学者</td><td>開発・API・ネットワークの 3 分野を体系的に学べる入口</td></tr></tbody></table>{' '}</div>{' '}<h3>1.3 CCNA（200-301）は必要か</h3>{' '}<p>{' '}必須ではありません。ただし、第 6 章（Network
                        Fundamentals）の知識が薄い方は、IP アドレス・VLAN・DHCP・DNS・NAT
                        を先に固めると学習が楽になります。{' '}</p>{' '}</div>{' '}</section>

<section className="section" id="sec-3" tabIndex={-1}>{' '}<h2>2. 試験範囲と学習ロードマップ</h2>{' '}<div className="prose">{' '}<h3>2.1 6 つのドメインと配点</h3>{' '}<div className="table-wrap">{' '}<table><thead><tr><th scope="col">#</th><th scope="col">ドメイン</th><th scope="col">配点</th><th scope="col">本ガイドの章</th></tr></thead><tbody><tr><td>1</td><td>Software Development and Design</td><td>15%</td><td>第 1 章</td></tr><tr><td>2</td><td>Understanding and Using APIs</td><td>20%</td><td>第 2 章</td></tr><tr><td>3</td><td>Cisco Platforms and Development</td><td>15%</td><td>第 3 章</td></tr><tr><td>4</td><td>Application Deployment and Security</td><td>15%</td><td>第 4 章</td></tr><tr><td>5</td><td>Infrastructure and Automation</td><td>20%</td><td>第 5 章</td></tr><tr><td>6</td><td>Network Fundamentals</td><td>15%</td><td>第 6 章</td></tr></tbody></table>{' '}</div>{' '}<Diagram id="dg1" />{' '}<h3>2.2 学習ロードマップ（依存関係）</h3>{' '}<p>{' '}初学者は、土台となる知識（Python・Git・ネットワーク）から順に進めると挫折しにくくなります。{' '}</p>{' '}<Diagram id="dg2" />{' '}<h3>2.3 8 週間の学習計画（目安）</h3>{' '}<div className="table-wrap">{' '}<table><thead><tr><th scope="col">週</th><th scope="col">学習内容</th><th scope="col">ハンズオンの例</th></tr></thead><tbody><tr><td>1</td><td>第 1 章：JSON/XML/YAML、Python パース、Git 基本</td><td>ローカルで Git リポジトリを作り、ブランチ・マージを体験</td></tr><tr><td>2</td><td>第 6 章：IP、VLAN、DHCP、DNS、NAT、ポート</td><td>サブネット計算を 10 問解く</td></tr><tr><td>3</td><td>第 2 章前半：HTTP、REST、ステータスコード、認証</td><td>curl / Postman で公開 API を呼ぶ</td></tr><tr><td>4</td><td>第 2 章後半：requests、Webhook、API スタイル</td><td>Python で REST API を呼び JSON を整形表示</td></tr><tr><td>5</td><td>{' '}第 3 章：Meraki・Catalyst Center・Webex・SDK、DevNet 資源{' '}</td><td>DevNet Sandbox で API を実行</td></tr><tr><td>6</td><td>第 4 章：Docker、CI/CD、OWASP、Bash</td><td>Dockerfile を書き、コンテナを起動</td></tr><tr><td>7</td><td>第 5 章：Ansible、Terraform、NETCONF/RESTCONF、YANG</td><td>Playbook 作成、RESTCONF で GET を実行</td></tr><tr><td>8</td><td>総復習：模擬問題、弱点補強、公式 Exam Topics との突合</td><td>時間を計って通し演習（120 分）</td></tr></tbody></table>{' '}</div>{' '}<div className="callout practice">{' '}<h3 className="callout-title">{' '}<i className="ti ti-bulb"></i>2.4 学習全体のベストプラクティス{' '}</h3>{' '}<div className="table-wrap">{' '}<table><thead><tr><th scope="col">{' '}原則{' '}</th><th scope="col">{' '}理由{' '}</th><th scope="col">{' '}具体策{' '}</th></tr></thead><tbody><tr><td>{' '}読むより動かす{' '}</td><td>{' '}試験は「コードを読んで何をしているか」を問うシナリオ型が多い{' '}</td><td>{' '}DevNet Sandbox で実際に API を実行する{' '}</td></tr><tr><td>{' '}公式ドキュメントを一次情報にする{' '}</td><td>{' '}ブログや教材は古い名称・古い手順が残りやすい{' '}</td><td>{' '}各プラットフォームの API リファレンスを確認する{' '}</td></tr><tr><td>{' '}最新の Exam Topics で範囲を確認{' '}</td><td>{' '}製品名や項目が更新される{' '}</td><td>{' '}受験直前に公式 PDF と自分のノートを突き合わせる{' '}</td></tr><tr><td>{' '}秘密情報を学習中から守る{' '}</td><td>{' '}実務で漏えい事故になる癖がつく{' '}</td><td>{' '}API キーは環境変数に置き、Git に入れない{' '}</td></tr><tr><td>{' '}間違えた問題を記録{' '}</td><td>{' '}弱点が可視化される{' '}</td><td>{' '}間違いノートをドメイン別に分ける{' '}</td></tr></tbody></table>{' '}</div>{' '}</div>{' '}</div>{' '}</section>
        </>
    );
}
